### ISSUE TITLE
Provide XFCE as an alternative to GNOME

### ISSUE THREAD

**Issue by anseyyyy** [ouspg/vms#5]
It could be beneficial to provide a virtual machine with XFCE installed in addition to the one with Gnome.

**Comment by Nicceboy** [comment]
I tried to add this, but Wayland support seems to be quite low, and not much plans about improving it. There are also some automation issues if you want to make it work smoothly in both UTM and Virtualbox (get screens to scale and clipboards work).

Maybe we can consider this some time later.
